# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [-l 79]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
    -   id: mypy
        stages: [manual]
-   repo: https://github.com/thg-consulting/whithercanada
    rev: 1dc71abeafc8bfdeb80b1ed820d408c12e06c04a
    hooks:
    -   id: check_commit_message
        stages: [prepare-commit-msg]
-   repo: local
    hooks:
    -   id: docs
        name: Generate documents
        pass_filenames: false
        entry: 'bin/generate_plugins.py'
        args: [--output=docs/]
        language: script
