name: CI

on: [push]


jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1

    - name: Install Python 3.9
      if: matrix.python == '3.9'
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3.9-dev python3.9-venv
        python3.9 -m pip install --upgrade pip setuptools
        python3.9 -m venv $HOME/venv-python3.9
        echo "::set-env name=VIRTUAL_ENV::$HOME/venv-python3.9"
        echo "::add-path::$HOME/venv-python3.9/bin"

    - uses: actions/setup-python@v1
      if: matrix.python != '3.9'
      with:
        python-version: ${{ matrix.python }}
        architecture: x64

    - name: Setup testing deps
      run: |
        python${{ matrix.python }} -m pip install -r requirements-dev.txt

    - name: Build
      run: |
        python${{ matrix.python }} -m pip install -e .

    - name: Test
      run: |
        python${{ matrix.python }} -m pytest --cov --cov-report=xml

    - name: Hook Tests
      run: |
        python${{ matrix.python }} bin/inspects.py tests/inspections --show-errors

    - name: Upload
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.codecov}}

